<?php

namespace app\models;
use yii\base\Model;
class TestForm extends  Model
{
    public $name;
    public $email;
    public $text;

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public  function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'text'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }


}